export * from './facility.service';
import { FacilityService } from './facility.service';
export * from './jobTitle.service';
import { JobTitleService } from './jobTitle.service';
export * from './key.service';
import { KeyService } from './key.service';
export * from './location.service';
import { LocationService } from './location.service';
export * from './locationType.service';
import { LocationTypeService } from './locationType.service';
export * from './permissions.service';
import { PermissionsService } from './permissions.service';
export * from './requesters.service';
import { RequestersService } from './requesters.service';
export * from './reservation.service';
import { ReservationService } from './reservation.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [FacilityService, JobTitleService, KeyService, LocationService, LocationTypeService, PermissionsService, RequestersService, ReservationService, UsersService];
