export * from './environment.service';
import { EnvironmentService } from './environment.service';
export * from './facilityType.service';
import { FacilityTypeService } from './facilityType.service';
export * from './keys.service';
import { KeysService } from './keys.service';
export * from './permissions.service';
import { PermissionsService } from './permissions.service';
export * from './places.service';
import { PlacesService } from './places.service';
export * from './position.service';
import { PositionService } from './position.service';
export * from './requesters.service';
import { RequestersService } from './requesters.service';
export * from './reservation.service';
import { ReservationService } from './reservation.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [EnvironmentService, FacilityTypeService, KeysService, PermissionsService, PlacesService, PositionService, RequestersService, ReservationService, UsersService];
