/**
 * key-keeper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { User } from './user';
import { Permission } from './permission';


export interface ChangeStatusReservationRequest { 
    id?: string | null;
    version?: number;
    active?: boolean;
    createdAt?: string;
    updatedAt?: string;
    permission?: Permission | null;
    user?: User | null;
    notes?: string;
    startDateTime: string;
    endDateTime: string;
    status: Status;
}
export namespace ChangeStatusReservationRequest {
}


