/**
 * key-keeper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Place } from './place';
import { TypeEnvironment } from './typeEnvironment';


export interface Environment { 
    id?: string | null;
    version?: number | null;
    active?: boolean;
    createdAt?: string;
    updatedAt?: string;
    name?: string;
    place?: Place | null;
    typeEnvironment?: TypeEnvironment | null;
}

