/**
 * key-keeper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Notifier } from './notifier';


export interface EventNotifier { 
    data?: Notifier;
    id?: string;
    name?: string;
    comment?: string;
    retry?: string;
}

