/**
 * key-keeper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LocationDto { 
    id: string;
    name: string;
    description: string;
    facility: string;
    locationType: string;
    maxCapacity: number;
    restricted?: boolean;
    openingTime: string;
    closingTime: string;
    responsibles?: Array<string>;
}

