/**
 * key-keeper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Requester } from './requester';
import { User } from './user';
import { Facility } from './facility';


export interface Permission { 
    id?: string | null;
    version?: number | null;
    active?: boolean;
    createdAt?: string;
    updatedAt?: string;
    facility?: Facility | null;
    requester?: Requester | null;
    user?: User | null;
    description?: string;
    startDateTime?: string;
    endDateTime?: string;
}

