/**
 * key-keeper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Permissions = 'MENU_EMPRESTIMOS' | 'MENU_AUTORIZACOES' | 'MENU_RECURSOS' | 'MENU_PARAMETRIZACOES' | 'MENU_GESTAO_ACESSOS' | 'EMPRESTIMOS' | 'HISTORICO' | 'SOLICITANTES' | 'PERMISSOES' | 'SALAS' | 'TIPO_AMBIENTE' | 'INSTALACOES' | 'CARGOS' | 'CONFIGURACAO' | 'USUARIOS' | 'ATRIBUICOES';

export const Permissions = {
    MenuEmprestimos: 'MENU_EMPRESTIMOS' as Permissions,
    MenuAutorizacoes: 'MENU_AUTORIZACOES' as Permissions,
    MenuRecursos: 'MENU_RECURSOS' as Permissions,
    MenuParametrizacoes: 'MENU_PARAMETRIZACOES' as Permissions,
    MenuGestaoAcessos: 'MENU_GESTAO_ACESSOS' as Permissions,
    Emprestimos: 'EMPRESTIMOS' as Permissions,
    Historico: 'HISTORICO' as Permissions,
    Solicitantes: 'SOLICITANTES' as Permissions,
    Permissoes: 'PERMISSOES' as Permissions,
    Salas: 'SALAS' as Permissions,
    TipoAmbiente: 'TIPO_AMBIENTE' as Permissions,
    Instalacoes: 'INSTALACOES' as Permissions,
    Cargos: 'CARGOS' as Permissions,
    Configuracao: 'CONFIGURACAO' as Permissions,
    Usuarios: 'USUARIOS' as Permissions,
    Atribuicoes: 'ATRIBUICOES' as Permissions
};

