/**
 * key-keeper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Requester } from './requester';
import { User } from './user';
import { Location } from './location';


export interface Permission { 
    id?: string | null;
    version?: number;
    active?: boolean;
    createdAt?: string;
    updatedAt?: string;
    overdue?: boolean;
    locations?: Array<Location>;
    requesters?: Array<Requester>;
    user?: User | null;
    description?: string;
    startDateTime: string;
    endDateTime: string;
}

