/**
 * key-keeper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequesterEmail } from './requesterEmail';
import { JobTitle } from './jobTitle';


export interface Requester { 
    id?: string | null;
    version?: number;
    active?: boolean;
    createdAt?: string;
    updatedAt?: string;
    name: string;
    emails: Array<RequesterEmail>;
    register?: string;
    jobTitle?: JobTitle | null;
    responsible?: boolean;
}

