/**
 * key-keeper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Position } from './position';


export interface Requester { 
    id?: string | null;
    version?: number | null;
    active?: boolean;
    createdAt?: string;
    updatedAt?: string;
    name?: string;
    email?: string;
    register?: string;
    position?: Position | null;
}

