/**
 * key-keeper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { Requester } from './requester';
import { User } from './user';
import { Permission } from './permission';
import { Key } from './key';
import { Location } from './location';


export interface Reservation { 
    id?: string | null;
    version?: number;
    active?: boolean;
    createdAt?: string;
    updatedAt?: string;
    overdue?: boolean;
    formattedPeriod?: string;
    permission?: Permission | null;
    requester?: Requester | null;
    location?: Location | null;
    user?: User | null;
    key?: Key | null;
    notes?: string;
    startDateTime: string;
    endDateTime: string;
    status: Status;
    notification?: boolean;
}
export namespace Reservation {
}


