/**
 * key-keeper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { User } from './user';
import { Permission } from './permission';
import { Facility } from './facility';


export interface Reservation { 
    id?: string | null;
    version?: number | null;
    active?: boolean;
    createdAt?: string;
    updatedAt?: string;
    permission?: Permission | null;
    facility?: Facility | null;
    user?: User | null;
    notes?: string;
    startDateTime?: string;
    endDateTime?: string;
    status?: Status;
}
export namespace Reservation {
}


