/**
 * key-keeper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { PermissionLocationSummaryDto } from './permissionLocationSummaryDto';
import { Requester } from './requester';


export interface ReservationCommand { 
    requester: Requester;
    status: Status;
    permission: PermissionLocationSummaryDto;
    startDateTime: string;
    endDateTime: string;
}
export namespace ReservationCommand {
}


