/**
 * key-keeper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Roles = 'EMPRESTIMOS' | 'HISTORICO' | 'SOLICITANTES' | 'PERMISSOES' | 'SALAS' | 'TIPO_AMBIENTE' | 'INSTALACOES' | 'CARGOS' | 'CONFIGURACAO' | 'USUARIOS' | 'ATRIBUICOES';

export const Roles = {
    Emprestimos: 'EMPRESTIMOS' as Roles,
    Historico: 'HISTORICO' as Roles,
    Solicitantes: 'SOLICITANTES' as Roles,
    Permissoes: 'PERMISSOES' as Roles,
    Salas: 'SALAS' as Roles,
    TipoAmbiente: 'TIPO_AMBIENTE' as Roles,
    Instalacoes: 'INSTALACOES' as Roles,
    Cargos: 'CARGOS' as Roles,
    Configuracao: 'CONFIGURACAO' as Roles,
    Usuarios: 'USUARIOS' as Roles,
    Atribuicoes: 'ATRIBUICOES' as Roles
};

