/**
 * key-keeper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Roles = 'VIEWER' | 'EDITOR' | 'MODERATOR' | 'MANAGER' | 'SUPER_ADMIN';

export const Roles = {
    Viewer: 'VIEWER' as Roles,
    Editor: 'EDITOR' as Roles,
    Moderator: 'MODERATOR' as Roles,
    Manager: 'MANAGER' as Roles,
    SuperAdmin: 'SUPER_ADMIN' as Roles
};

