/**
 * key-keeper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Screen = 'EMPRESTIMOS' | 'HISTORICO' | 'SOLICITANTES' | 'PERMISSOES' | 'SALAS' | 'TIPO_AMBIENTE' | 'INSTALACOES' | 'CARGOS' | 'CONFIGURACAO' | 'USUARIOS' | 'ATRIBUICOES';

export const Screen = {
    Emprestimos: 'EMPRESTIMOS' as Screen,
    Historico: 'HISTORICO' as Screen,
    Solicitantes: 'SOLICITANTES' as Screen,
    Permissoes: 'PERMISSOES' as Screen,
    Salas: 'SALAS' as Screen,
    TipoAmbiente: 'TIPO_AMBIENTE' as Screen,
    Instalacoes: 'INSTALACOES' as Screen,
    Cargos: 'CARGOS' as Screen,
    Configuracao: 'CONFIGURACAO' as Screen,
    Usuarios: 'USUARIOS' as Screen,
    Atribuicoes: 'ATRIBUICOES' as Screen
};

