/**
 * key-keeper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Status = 'EMPRESTIMO' | 'AGENDADO' | 'CANCELADO' | 'CONCLUIDO';

export const Status = {
    Emprestimo: 'EMPRESTIMO' as Status,
    Agendado: 'AGENDADO' as Status,
    Cancelado: 'CANCELADO' as Status,
    Concluido: 'CONCLUIDO' as Status
};

