/**
 * key-keeper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Status = 'RESERVATION' | 'AGENDADO' | 'AND_PROGRESS';

export const Status = {
    Reservation: 'RESERVATION' as Status,
    Agendado: 'AGENDADO' as Status,
    AndProgress: 'AND_PROGRESS' as Status
};

