/**
 * key-keeper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Status = 'LOAN' | 'SCHEDULED' | 'COMPLETED';

export const Status = {
    Loan: 'LOAN' as Status,
    Scheduled: 'SCHEDULED' as Status,
    Completed: 'COMPLETED' as Status
};

