/**
 * key-keeper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Roles } from './roles';


export interface UserDto { 
    email?: string;
    name?: string;
    password: string;
    username: string;
    roles: Roles;
}
export namespace UserDto {
}


